name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'tools/*'
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'tools/*'
  # Uncomment for a weekly test
  # This way we will catch incompatible changes quickly.
  # schedule:
  #   # At 5:39am each Tuesday (UTC)
  #   - cron: '39 5 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: [ minimal, latex, tinytex ]
    # container:
    #   image: jdutant/quarto-${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # This shows how to build directly from docker
      # (we could use make too)
      - name: Build image
        run: |
          docker build \
          --build-arg TARGETOS=linux \
          --build-arg TARGETARCH=amd64 \
          -f Dockerfile.${{ matrix.image }} \
          -t quarto-${{ matrix.image }} .

      - name: Test image
        run: |
          make -B match \
            QUARTO="docker run --rm --volume $(pwd):/data quarto-${{ matrix.image }}"
