name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'tools/*'
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'tools/*'
  # Uncomment for a weekly test
  # This way we will catch incompatible changes quickly.
  # schedule:
  #   # At 5:39am each Tuesday (UTC)
  #   - cron: '39 5 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    # container:
    #   image: pandoc/latex:${{ matrix.pandoc }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # This shows how to build directly from docker
      # (we could use make too)
      - name: Build minimal image
        run: |
          docker build \
          --build-arg TARGETOS=linux \
          --build-arg TARGETARCH=amd64 \
          -f minimal.dockerfile -t quarto .

      - name: Test minimal image
        run: |
          make -B match \
            QUARTO="docker run --rm --volume $(pwd):/data quarto"

      - name: Build latex image
        run: |
          docker build \
          --build-arg TARGETOS=linux \
          --build-arg TARGETARCH=amd64 \
          -f latex.dockerfile -t quarto-latex .

      - name: Test latex image
        run: |
          make -B latex \
            QUARTO="docker run --rm --volume $(pwd):/data quarto-latex"

      - name: Build tinytex image
        run: |
          docker build \
          --build-arg TARGETOS=linux \
          --build-arg TARGETARCH=amd64 \
          -f tinytex.dockerfile -t quarto-tinytex .

      - name: Test tinytex image
        run: |
          make -B latex \
            QUARTO="docker run --rm --volume $(pwd):/data quarto-tinytex"

